# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# If constructed on website root, no need to specify
baseurl: ""
url: ""
# If constructed other than website root, specify directory
#baseurl: "........."
#url: ""

permalink: pretty

include:
  - .htaccess
  - _pages

exclude:
  - _site
  - Gemfile
  - Gemfile.lock
  - vendor/

sass:
  sass_dir: _sass

# plugins for various features
plugins:
  - jekyll-sitemap
  - jekyll-lunr-js-search

sitemap:
  changefreq: weekly

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


exclude_from_search: true

lunr_search:
  excludes: [
    "rss.xml",
    "atom.xml",
    "sitemap.xml",
    "search.html",
    "search.json",
    "robots.txt",
    "_data",
    "_includes",
    "_layouts",
    "_posts",  # Exclude all posts
    "_sass",
    "main.css",
    "/css/main.css",
    "js",
    "vendor",
    "Gemfile",
    "Gemfile.lock",
    "_site",
    "assets/img/", # Exclude a specific folder
  ]


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
